### PR TITLE
bn-fixed-crosslinks-in-T1-&-T4

### PR DESCRIPTION
**Pull request by bnorikane**
Changed link to T1 in t4_household_lockdown.md. Replaced underscores with hyphens

### CODE REVIEW

**Comment by bnorikane** [comment]
2nd commit:
Fix broken link to T10 on line 31 in T1

**Comment by bnorikane** [comment]
I checked all the cross links in T1 and have corrected them.
Working on T4

**Comment by bnorikane** [comment]
Checked all crosslinks in T4 and fixed them.

**Comment by The-Kergan** [comment]
@bnorikane thanks for fixing the links. @zuedev can you please enable spell checker so this can be closed? Thanks!

**Comment by zuedev** [comment]
@The-Kergan Done! :)

**Pull request merged**
